dir_output : data/hybridization_probability/datasets # path to the folder where the dataset will be stored
oligo_length_min: 15  # minimum length of the oligos
oligo_length_max: 100  # maximum length of the oligos
splits_size: [0.5, 0.2, 0.3]  # train , validation and test splits
file_genes: data/genes/custom_3.txt  # path to the file containing the desired genes
dataset_size: 6500 # total number of entries of the dataset
oligos_per_region: 1000 # maximun number of oligo per region for which teh off targets are searched
concentration: 1e-6  # strand concentrations int the tube
n_jobs: 5  # number of available CPUs (if None the maximum number of CPUs will be used)
seed: 42
nupack_cache: 8.0

######### only for custom source ##########
source: custom # required: indicate that own annotation should be used
source_params:
    file_annotation: data/annotations/custom_GCF_000001405.40_GRCh38.p14_genomic_chr16.gtf # required: GTF file with gene annotation
    file_sequence: data/annotations/custom_GCF_000001405.40_GRCh38.p14_genomic_chr16.fna # required: FASTA file with genome sequence
    files_source: NCBI # optional: original source of the genomic files
    species: Homo_sapiens # optional: species of provided annotation, leave empty if unknown
    taxon: vertebrate_mammalian # optional: taxon of the species we are intereste, only for source: ncbi
    annotation_release: 110 # optional: release number of provided annotation, leave empty if unknown
    genome_assembly: GRCh38  # optional: genome assembly of provided annotation, leave empty if unknown
genomic_regions:
  gene: false
  exon: true
  exon_exon_junction: false
  cds: false
  intron: false

######### alignment method ##########
alignment_method: blastn
search_parameters:
  perc_identity: 80
  strand: "minus" # this parameter is fixed, if reference is whole genome, consider using "both"
  word_size: 10
  outfmt: 6 qseqid sseqid length qstart qend qlen qseq sstart send sseq sstrand
hit_parameters:
  coverage: 50 # could be turned into min_alignment_length
names_search_output:
  - query
  - reference
  - alignment_length
  - query_start
  - query_end
  - query_length
  - query_sequence
  - reference_start
  - reference_end
  - reference_sequence
  - reference_strand